
INSERT INTO APPSTOREUSER.ACCOUNT (USER_ID, ACCOUNT_TYPE, CREATE_TIMESTAMP, EMAIL, LOGIN, MODIFY_TIMESTAMP, NAME, PASSWORD, SURNAME, VERSION) VALUES (-10, 'ADMIN', CURRENT_TIMESTAMP, 'testowyMail1@op.pl', 'admin', CURRENT_TIMESTAMP, 'Staszek', 'adminPass', 'Adminowy', 1)
INSERT INTO APPSTOREUSER.ACCOUNT (USER_ID, ACCOUNT_TYPE, CREATE_TIMESTAMP, EMAIL, LOGIN, MODIFY_TIMESTAMP, NAME, PASSWORD, SURNAME, VERSION) VALUES (-20, 'MOD', CURRENT_TIMESTAMP, 'testowyMail2@op.pl', 'moder', CURRENT_TIMESTAMP, 'Tester', 'moderPass', 'Moderowy', 1)
INSERT INTO APPSTOREUSER.ACCOUNT (USER_ID, ACCOUNT_TYPE, CREATE_TIMESTAMP, EMAIL, LOGIN, MODIFY_TIMESTAMP, NAME, PASSWORD, SURNAME, VERSION) VALUES (-30, 'USER', CURRENT_TIMESTAMP, 'testowyMail3@op.pl', 'user', CURRENT_TIMESTAMP, 'StarszyTester', 'userPass', 'Userowy', 1)

INSERT INTO APPSTOREUSER.APPS (APP_ID, APP_FILE, APP_NAME, APP_VERSION, DESCRIPTION, OPERATING_SYSTEM, VERSION, AUTHOR_ID) VALUES (-100, CAST(x'7070' AS BLOB), 'Pierwsza_Appka', '78.5.54.0', 'To pierwsza appka testowa, bardzo fajna', 'Windows', 1, -20)
INSERT INTO APPSTOREUSER.APPS (APP_ID, APP_FILE, APP_NAME, APP_VERSION, DESCRIPTION, OPERATING_SYSTEM, VERSION, AUTHOR_ID) VALUES (-200, CAST(x'707456' AS BLOB), 'Druga_Appka', '1.11.0.0', 'To druga appka testowa, bardzo fajna z długim opisem opisem opisem opisem opisem opisem opisem opisem', 'iOS', 1, -30)
INSERT INTO APPSTOREUSER.APPS (APP_ID, APP_FILE, APP_NAME, APP_VERSION, DESCRIPTION, OPERATING_SYSTEM, VERSION, AUTHOR_ID) VALUES (-300, CAST(x'70' AS BLOB), 'Trzecia_Appka', '2.100.10.0', 'To opis', 'Other', 1, -20)
INSERT INTO APPSTOREUSER.APPS (APP_ID, APP_FILE, APP_NAME, APP_VERSION, DESCRIPTION, OPERATING_SYSTEM, VERSION, AUTHOR_ID) VALUES (-400, CAST(x'700000' AS BLOB), 'Czwarta_Appka', '8.1.1.0', 'To opisyyyyyyyyyy', 'iOS', 1, -10)

INSERT INTO APPSTOREUSER.FILESDATA (FILE_APP_ID, FILE_NAME, FILE_SIZE, FILE_TYPE) VALUES (-100, 'Raz.txt', 2, 'text/plain')
INSERT INTO APPSTOREUSER.FILESDATA (FILE_APP_ID, FILE_NAME, FILE_SIZE, FILE_TYPE) VALUES (-200, 'Dwa.txt', 3, 'text/plain')
INSERT INTO APPSTOREUSER.FILESDATA (FILE_APP_ID, FILE_NAME, FILE_SIZE, FILE_TYPE) VALUES (-300, 'Trzy.txt', 1, 'text/plain')
INSERT INTO APPSTOREUSER.FILESDATA (FILE_APP_ID, FILE_NAME, FILE_SIZE, FILE_TYPE) VALUES (-400, 'Cztery.txt', 3, 'text/plain')